[build]
    command = "npm run build"
    publish = "dist"
    functions = "functions"

[dev]
    command = "npm run dev"
    port = 5000
    targetPort = 3000
    publish = "dist"
    autoLaunch = false
    framework = "#custom"
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
